### ISSUE TITLE
descaler is invoked even when it is not used

### ISSUE THREAD

**Issue by l00tzOMG** [Irrational-Encoding-Wizardry/lvsfunc#8]
I don't know if it is a bug or a feature but the descaler library is invoked, when I wanted to use the edgefixer function. If `libdescale.dll` is not loaded before calling `import lvsfunc` VapourSynth throws a missing namespace error referring to line 899 in lvsfunc.py, where `descaler` is defined. If it is loaded before the import command, the error disappears and the script just runs fine.

As far as I understand descaler is not required for edgefixer...

VapourSynth version: R49-RC1
OS: Win 10 x64

BTW: what is the difference between MonoS's edgefixer and sekrit's one (https://github.com/sekrit-twc/EdgeFixer)?

Thank you very much in advance!

**Comment by LightArrowsEXE** [comment]
Hello, could you double-check to see if this update fixes it? 

The issue was not relevant to `edgefixer` specifically, but to `smarter_descale`, since it calls for an object in the parameters, which I've now moved to inside the function as a fix.

As for the differences between MonoS' and sekrit's edgefixers, at base they appear to work basically identically in my eyes. The only difference with sekrit's is that it has luminance balancing, but I don't think it works all that well, so I just stuck with MonoS' version for years by now.

Hope these answer all your questions!

**Comment by l00tzOMG** [comment]
Sweet, it works. Thank you. Now if I import lvsfunc and make a BlankClip no additional libs are required :)

Regarding the difference between the two: thanks for the explanation.
