### ISSUE TITLE
Avisynth port updates

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/lvsfunc#85]
A lot of Avisynth ports are very old, and the filters ported have since been updated to be faster, more precise, and offer more functionality. This issue has been made to take a look at all the ports within lvsfunc that could use re-porting. This issue will be updated at a later date once I find time to look through the module and find what is and isn't an AVS port. Any help with listing them is appreciated.

Functions that require updating:
[ ] - [masked_dha](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Masked_DHA.avsi) (?)

To be updated.

**Comment by LightArrowsEXE** [comment]
@NSQY In [this post](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/issues/74#issuecomment-1029035634) you were talking about AVS ports being outdated. Do you know of any ports in this \*func that is outdated? I was only able to find `masked_dha`, and I'm not even entirely sure it's outdated.

**Comment by NSQY** [comment]
Nothing currently strikes me as being a problem, my comment was mostly a preemptive warning for future ports. If I were to guess, the main area of trouble would be functions ported before or around the time that AVS+ was being introduced.

With AVS+, they introduced many features that VS users take for granted (high precision formats, (pseudo) multi-threading, etc. Anything ported to VS before this would have had to take certain liberties. In the years since, there has been a constant and ongoing effort to modernize AVS(+) functions to the point where many of them are faster than their equivalent VS sisters. 

By the way, to my knowledge expr will generally perform better than C/CPP/Rust plugins at the cost of complexity, this is why AVS functions look the way they do.

**Comment by DonCanjas** [comment]
Make sure you're using this updated version of vinverse and please include the function vinverse2, it's much better https://github.com/Asd-g/vinverse

**Comment by po5** [comment]
lvsfunc's vinverse is not a straight port, @Setsugennoao rewrote it with his specific needs.  
On minor combing it retains detail much better instead of turning it into ugly blocking.

**Comment by DonCanjas** [comment]
> On minor combing it retains detail much better instead of turning it into ugly blocking.

Vinverse2 is like that too, whichone is better I do not know

**Comment by LightArrowsEXE** [comment]
Basically every useful AVS port has been moved to different packages by now.
